version: '3.3'

services:
  nginx:
    restart: always
    depends_on:
      - backend
    image: "nginx:latest"
    ports:
      - "80:80"
    networks:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

  frontend:
    restart: always
    depends_on:
      - backend
    build: "./frontend"
    image: "frontend:latest"
    networks:
      - app

  backend:
    restart: always
    depends_on:
      - pgsql
    build: "./backend"
    image: "backend:latest"
    networks:
      - app
    volumes:
      - ./backend/resources/tsconfig.json:/home/app_backend/backend/tsconfig.json:ro
      - v_migrations:/home/app_backend/backend/prisma/migrations:rw
      - v_upload:/home/app_backend/content/upload:rw
    environment:
      - FTAPI_URL
      - FTAPI_AUTH
      - FTAPI_TOKEN
      - FTAPI_USERDATA
      - FTAPI_CLIENTID
      - FTAPI_SECRET
      - FTAPI_REDIRECTURI
      - FTAPI_SCOPE
      - DATABASE_URL
      - JWT_SECRET

  pgsql:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - v_pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

networks:
  app:

volumes:
  v_migrations:
  v_pgsql:
  v_upload: