# server {
# 	listen 80;
# 	server_name ft_transcendence.io;
# 	return 301 https://localhost;
# }

upstream frontend {
  server frontend:3000;
}

upstream backend {
  server backend:8000;
}
server
{
	listen			80;
	listen			443 ssl;
	listen			[::]:443 ssl;
	allow			0.0.0.0/0;
	server_name		localhost;
	ssl_certificate		/etc/nginx/ssl/ft_transcendence.crt;
	ssl_certificate_key	/etc/nginx/ssl/ft_transcendence.key;
	ssl_protocols		TLSv1.2 TLSv1.3;
	root			/var/www/html/frontend/build;
	index			index.html
	error_log /dev/stdout;
	access_log /dev/stdout;

	# add_header 'Access-Control-Allow-Origin' '*';
	# add_header 'Access-Control-Allow-Credentials' 'true';
	# add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
	# add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

  location / {
      proxy_pass http://frontend;
  }

#   location /sockjs-node {
#       proxy_pass http://frontend;
#       proxy_http_version 1.1;
#       proxy_set_header Upgrade $http_upgrade;
#       proxy_set_header Connection "Upgrade";
#   }
  
  location /api {
      rewrite /backend/(.*) /$1 break;
      proxy_pass http://backend;
  }
}